SELECT * FROM customer_behaviour;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) As 'revenue' FROM customer_behaviour
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount, (SELECT AVG(purchase_amount) FROM customer_behaviour) FROM customer_behaviour
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_behaviour);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS 'Avg_rating' FROM customer_behaviour
GROUP BY item_purchased 
ORDER BY Avg_rating DESC LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount)) AS 'Avg_shipping' FROM customer_behaviour
WHERE shipping_type = 'Express' OR shipping_type = 'Standard'
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
SELECT subscription_status, COUNT(subscription_status) AS total_members, ROUND(AVG(purchase_amount))AS purchase, SUM(purchase_amount) AS total_revenue FROM customer_behaviour
GROUP BY subscription_status ;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rates
FROM customer_behaviour
GROUP BY item_purchased
ORDER BY discount_rates DESC LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
WITH customer_type AS(
	SELECT customer_id, previous_purchases, 
    (CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END
    ) AS customer_segment FROM customer_behaviour
) 
SELECT customer_segment, COUNT(*) AS total_cutomer FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH most_purchased_items AS (SELECT category, item_purchased, COUNT(customer_id) AS 'total_orders', 
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS `ranking` 
FROM customer_behaviour
GROUP BY category, item_purchased)
SELECT ranking, item_purchased, total_orders, category FROM most_purchased_items
WHERE ranking <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
WITH cte AS(SELECT customer_id, subscription_status, previous_purchases, 
IF(previous_purchases > 5 AND subscription_status = 'Yes',1,0) AS subscriber_return FROM customer_behaviour)
SELECT COUNT(customer_id) FROM cte WHERE subscriber_return = 1;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS 'revenue' FROM customer_behaviour
GROUP BY age_group
ORDER BY revenue DESC